name: Lint on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

env:
  NODE_VERSION: 10

jobs:
  linting:
    name: Linting before merge
    runs-on: ubuntu-18.04
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Linting
        run: yarn lint
