name: Lint on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

env:
  NODE_VERSION: 10

jobs:
  linting:
    name: Linting before merge
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v1

      - name: yarn install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Linting
        run: yarn lint
