name: Shell Commands

on: [push]

jobs:
  linting:
    name: Linting before merge
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: borales/actions-yarn@v3
        with:
          cmd: install
